---
dist: bionic
language: python
python: "3.7.1"
cache:
  - npm
  - pip
  - yarn
services:
  - docker

env:
  global
  - REQ_URL="https://travis-requirements.s3.us-south.cloud-object-storage.appdomain.cloud/requirements.travis.txt"

# script:
#   - pre-commit run --all-files

jobs:
  include:
    - stage: Run checks and tests
      install:
        - pip3 install -r ${REQ_URL}
      script:
        - pre-commit run --all-files
        - docker run --rm -i hadolint/hadolint:v1.15.0 < $(find . type f -name "Dockerfile")
    -
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
        - source ~/.nvm/nvm.sh
        - nvm install v12.13.1
      script:
        - npm test
